apiVersion: aws.platformref.upbound.io/v1alpha1
kind: Cluster
metadata:
  name: platform-ref-aws
  namespace: default
spec:
  compositeDeletePolicy: Foreground
  parameters:
    id: platform-ref-aws
    region: us-west-2
    version: "1.27"
    iam:
      # replace with your custom arn like:
      # roleArn: arn:aws:iam::123456789:role/AWSReservedSSO_AdministratorAccess_d703c73ed340fde7
      roleArn: ${data.aws_eks_iam_default_admin}
    nodes:
      count: 3
      instanceType: t3.small
  writeConnectionSecretToRef:
    name: platform-ref-aws-kubeconfig
